format_version: 9
pipelines:
  pipeline_code_demo:
    group: defaultGroup
    materials:
      backend:
        git: https://github.com/sandeepraina-dsd19/spring-boot-h2-war-tomcat.git
        branch: master
    stages:
      - Build_Demo_Project_Stage:
          clean_workspace: true
          jobs:
            build_task:
              tasks:
                - exec:
                    run_if: passed
                    command: mvn
                    arguments:
                    - package
      - Start_Tomcat_Stage:
          clean_workspace: true
          jobs:
            start_tomcat_task:
              tasks:
                - exec:
                    run_if: passed
                    command: cmd
                    arguments:
                    - start_tomcat.sh
                    - C:/apache-tomcat-9.0.62 
      - Deploy_Project_Stage:
          clean_workspace: true
          jobs:
            deploy_project_task:
              tasks:
                - exec:
                    run_if: passed
                    command: mvn
                    arguments:
                    - tomcat7:deploy
